### ISSUE TITLE
keep alive with azure redis service

### ISSUE THREAD

**Issue by devNum42** [NodeRedis/node-redis#1632] opened 2021-07-20 11:58 UTC
### Issue

If there is no requests to redis (azure redis service) after 10 mins we get disconnect and connect.
in the redis client the socket_keepalive is set to true.

it looks like the keep alive is not working well with azure redis service

---

### Environment

 - **Node.js Version**: `12.14.0`
 - **Redis Version**: `3.1.2`
 - **Platform**: `Mac OSX 11.4`

**Comment by leibale** [comment] 2021-07-27 17:09
duplicate of #1598

**Closed by leibale** 2021-07-27 17:09 UTC
