### ISSUE TITLE
Cluster Support

### ISSUE THREAD

**Issue by sangianpatrick** [NodeRedis/node-redis#1540] opened 2020-10-08 00:09 UTC
### Needs to create cluster with multiple redis server (nodes)

> Actually We're working with Go and redis setup is a cluster mode with 6 nodes (3 masters 3 slaves).
In some use cases the needs of nodejs is priority like realtime server with socket.io.
We need to put the redis cluster mode to socket.io redis adapter but we actually don't get the way yet to configure it.

---

### Environment

 - **Node.js Version**: `12`
 

 - **Redis Version**: `6`
 

 - **Platform**: `Alpine Linux`

**Comment by leibale** [comment] 2021-03-04 23:06
Duplicate of #574

**Closed** 2021-03-04 23:06 UTC
